import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <p>HEADER</p>
        </header>
        <div className={styles.content}>
          <aside className={styles.sidebar}>
            <p>SIDEBAR</p>
          </aside>
          <main className={styles.main}>
            <p>MAIN</p>
          </main>
        </div>
        
      </div>
      
    </>
  )
}
